In [2]:
def func():
    try:
        if 5%0==0:
            print(True)
    except:
        print("not possible")
    
func()



not possible


In [4]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

sentence_list=[(sub+" "+verb+"  "+obj) for sub in subjects for verb in verbs for obj in objects]
for sentence in sentence_list:
    print(sentence)



Americans  play  Baseball
Americans  play  Cricket
Americans  watch  Baseball
Americans  watch  Cricket
Indians play  Baseball
Indians play  Cricket
Indians watch  Baseball
Indians watch  Cricket


In [2]:
import numpy as np
def vander_matrix(vector, n, increasing=False):
    
    if not increasing:
        matrix = np.array([i**(n-1-j) for i in vector for j in range(n)]).reshape(vector.size,n)
    elif increasing:
        matrix = np.array([i**j for i in vector for j in range(n)]).reshape(vector.size,n)
    
    return matrix



inputvector = np.array([1,2,3,4,5,6])
no_col_opmat = len(inputvector)
op_matx_dec_order = vander_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = vander_matrix(inputvector,no_col_opmat,True)
print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")

The input array is: [1 2 3 4 5 6] 

Number of columns in output matrix should be: 6 

Vander matrix of the input array in decreasing order of powers:

 [[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]
 [7776 1296  216   36    6    1]] 

Vander matrix of the input array in increasing order of powers:

 [[   1    1    1    1    1    1]
 [   1    2    4    8   16   32]
 [   1    3    9   27   81  243]
 [   1    4   16   64  256 1024]
 [   1    5   25  125  625 3125]
 [   1    6   36  216 1296 7776]] 

